# Generated by Django 4.1 on 2022-09-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='lte_exist',
            field=models.CharField(max_length=50),
        ),
    ]
